version: '2'
services:
    hamsa_api:
        depends_on:
            - hamsa_db
        build: hamsa-api/.
        image: hap/hamsa-api
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./hamsa-server/server/:/var/www/html/
            - ./images/:/var/www/images
        env_file: database.env
        links:
            - "hamsa_db:database"


    hamsa_db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        volumes:
            - ./hamsa-database:/docker-entrypoint-initdb.d
        restart: always
        env_file: database.env

    hamsa_admin:
        depends_on:
          - hamsa_api
        build: hamsa-admin/.
        image: hap/hamsa-admin
        ports:
          - "3000:3000"
          - "10001:10001"
        volumes:
          - ./hamsa-admin:/usr/src/app
        links:
          - "hamsa_api:api"
        command: npm run dev