<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Test image metadata</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            .metadata {
                text-align: left;
                width: 70%;
                padding-left: 60px;
            }
        </style>
    </head>
    <body>
        <h1>HAMSA test</h1>
        <p>Test metadata reading from images</p>

        <form action="" method="POST" enctype="multipart/form-data">
            <p>Image: <input type="file" name="file"></p>
            <p><input type="submit">Upload and read data</input></p>
        </form>
        
        <div class="metadata">
        <?php if (isset($data)) : ?>
            <?php foreach($data as $key => $value) { ?>
                <p><b><?= htmlspecialchars($key); ?>:</b> <?= htmlspecialchars(print_r($value, true)); ?></p>
            <?php } ?>
        <?php endif; ?>
        </div>
    </body>
</html>
